# For running tests on Travis-CI
FROM haskell
MAINTAINER David Parrish <daveparrish@tutanota.com>

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
 xz-utils \
 make \
 libgpgme11-dev

WORKDIR /root/build
CMD stack setup \
 && stack build --haddock --no-haddock-deps \
 && stack test --test-arguments "-p !**/*_prompt"

ADD . /root/build
