#!/bin/bash

# First (optional) parameter is the 'stack.yaml' file.
if [ -z "$1" ]; then
  stack_yaml="stack.yaml"
else
  stack_yaml="$1"
fi

# Wrapper to run tests without prompts on Travis CI
docker-compose run --rm tests stack --stack-yaml "$stack_yaml" test --test-arguments '-p !**/*_prompt'
