name: CI

on: push

env:
  STACK_YAML: stack.yaml

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Set up HLint'
        uses: haskell/actions/hlint-setup@v1

      - name: 'Run HLint'
        uses: haskell/actions/hlint-run@v1

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker-compose build --pull
      - run: docker-compose run --rm tests stack --stack-yaml ${STACK_YAML} setup
      - run: docker-compose run --rm tests stack --stack-yaml ${STACK_YAML} clean
      - run: docker-compose run --rm tests stack --stack-yaml ${STACK_YAML} build --haddock --no-haddock-deps
      - run: ./runtests-ci.sh ${STACK_YAML}
