name: CI

on: push

env:
  STACK_YAML: stack.yaml

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Set up HLint'
        uses: haskell/actions/hlint-setup@v1
        with:
          version: 3.2.7

      - name: 'Run HLint'
        uses: haskell/actions/hlint-run@v1
        with:
          fail-on: 'warning'

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v1
        with:
      - run: stack test --test-arguments='--pattern=!/NoCi/'
