name: CI

# triggering on PRs means the workflows are also triggered on PRs from forks (only push doesn't)
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  STACK_YAML: stack.yaml

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Set up HLint'
        uses: haskell/actions/hlint-setup@v1
        with:
          version: 3.2.7

      - name: 'Run HLint'
        uses: haskell/actions/hlint-run@v1
        with:
          fail-on: 'warning'

  test:
    runs-on: ubuntu-latest
    name: test ghc ${{ matrix.ghc-version }}
    strategy:
      matrix:
        ghc-version: [8.8, 9.0, 9.2, latest]
    steps:
      - run: sudo apt-get install -y libgpgme-dev
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc-version }}
          enable-stack: true
      - run: stack test --test-arguments='--pattern=!/NoCi/'

  docs:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y libgpgme-dev
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v1
        with:
          # can't build docs on latest ghc, because https://github.com/haskell/cabal/issues/8104
          ghc-version: 8.8
          enable-stack: true
      - run: cabal update
      - run: cabal build
      - run: cabal v2-haddock --builddir="$(mktemp -d dist-docs.XXXXXX)" --haddock-for-hackage --enable-doc
