name: CI

on: push

env:
  STACK_YAML: stack.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: docker-compose build --pull
      - run: docker-compose run --rm tests stack --stack-yaml ${STACK_YAML} setup
      - run: docker-compose run --rm tests stack --stack-yaml ${STACK_YAML} clean
      - run: docker-compose run --rm tests stack --stack-yaml ${STACK_YAML} build --haddock --no-haddock-deps
      - run: ./runtests-ci.sh ${STACK_YAML}
